### ISSUE TITLE
Improve logic when re-paging results (semi-bug)

### ISSUE THREAD

**Issue by vykozlov** [EOSC-synergy/eosc-perf#137]
**Describe the bug**
If results are distributed on more than one page, one selects some results on e.g. 2nd, 3d page (not the first one) and decides to change how many results can be seen "per page" system returns "Error while loading results"

**To Reproduce**
1. Go to https://performance.services.fedcloud.eu/result-search
2. Click on 'Benchmark', select e.g. 'thechristophe/openbench-c-ray:latest'
3. Scroll down, results are shown across two pages (20 results per page)
4. Go to page 2
5. Go down on the page, change "Results per page:" from 20 to e.g. 50
6. See error ""Error while loading results"

**Expected behavior**
Results are re-arranged on pages according to new 'per-page request', selected results remain selected. IF page 2 (as in the example above) not available, return last possible page (in that example, page 1 currently)

**Additional context**
The problem seems to be the following: e.g. there are 30 results, if "per page = 20", there are two pages. If now on  "page 2" one requests "per page = 50", there is no anymore "page 2" and the error is returned. For a user, it will be convenient to return in such a case "last available page", i.e. "page 1" in the example.

**Comment by TheChristophe** [comment]
The issue is unrelated to selection:
 - backend returns 404 when one requests a page that does not exist
 - example: backend has 40 results, frontend go to page 2, select 50 per page => frontend asks for results 51+, but there's only 40, so there is no 2nd page => 404

I'm gonna take it as a frontend bug as it should reset (or recalculate) the page number when changing the number of results to display. Backend response is fine (explicit 404, there is no data fulfilling the request)
