### ISSUE TITLE
Upload benchmark results to the system : Failed to submit new site.

### ISSUE THREAD

**Issue by vykozlov** [EOSC-synergy/eosc-perf#24]
**Description:**
Selected JSON file
Benchmark: someone/benchmark
Execution site:
Custom site: site name "IFCA-LCG2", site IP: "https://mesos.cloud.ifca.es", optional description: "marathon + V100 GPU"
Selected tags
Checked license

Got: Error! Failed to submit new site.

**Expected**: 
benchmark results uploaded and some notification about validation of a new site.

**Comment by TheChristophe** [comment]
Can reproduce by submitting two results one after another, with same custom site info.
This probably happens because the cview tries adding the new site again without checking if a site with such info already exists (which could not have been selected from the dropdown because it was not approved yet).

**Comment by vykozlov** [comment]
This means, that a new site can be added, even if the whole "Upload result" was unsuccessful? This also seems to happen for tags: a new tag is added, even if the "Upload result" was not successful.

**Comment by mlbehr** [comment]
861d40bc13dc22797e09461bc812f2558fb47091: Custom sites are only added if JSON upload succeeds
