### ISSUE TITLE
"Infrastructure Manager" does not point anywhere

### ISSUE THREAD

**Issue by vykozlov** [EOSC-synergy/eosc-perf#30]
**Is your feature request related to a problem? Please describe.**
In the top menu "Infrastructure Manager" link does not point anywhere, should point to:
https://appsgrycap.i3m.upv.es:31443/im-dashboard/login

**Describe the solution you'd like**
point to:
https://appsgrycap.i3m.upv.es:31443/im-dashboard/login

**Comment by TheChristophe** [comment]
This was solved in https://github.com/EOSC-synergy/eosc-perf/commit/5b1852e55e20928e38f51b3459568a1d46cea8fa
The test node was out of date; I do not use it to develop because it is awfully slow, so I do not regularly pull git on it. The button should work now, with the link configurable in the config.yaml.
