### ISSUE TITLE
Admin: Test result report review returns 502

### ISSUE THREAD

**Issue by BorjaEst** [EOSC-synergy/eosc-perf#41]
**Describe the bug**
The menu link: "__Secret admin menu__" > "__Test result report review__" returns "__502 Bad Gateway__"

**To Reproduce**
1. Click on  "__Secret admin menu__" > "__Test result report review__"

**Expected behavior**
A page with result reports should be displayed.

**Comment by TheChristophe** [comment]
Do note that this button was only added as a way to get to a result report page in a time when the navigation to this was impossible (e.g., the search page was missing) and was by no means intended to stay in the final product.

That aside, the issue was a missing redirect in case there's no available report. I'll push a commit to fix it, please reopen the issue should it reoccur.
