### ISSUE TITLE
Admin: Site review points allways to the same site review Or crashes

### ISSUE THREAD

**Issue by BorjaEst** [EOSC-synergy/eosc-perf#43]
**Describe the bug**
The Remove/Approve Site at "**Secret admin menu**" > "__Test site review__" points always to the same site (even if re-enter). Also it crashes the server sometimes.

**To Reproduce**
1. Go to "**Secret admin menu**" > "__Test site review__"
2. Click on 'Remove site' or 'Approve site'
3. Check if new site results were added (should? As the only way to add a site is with a new result upload)
4. See: 
- There is no new data with the site at "search"
- When Go again on "**Secret admin menu**" > "__Test site review__" the same approval appears
- If the step is repeated several times, it might break the server (but it goes up after some minutes again)

**Expected behavior**
1. The site reports should be available at the search lists
2. Confirmation that the site was Removed/Approved only if it really happened!
3. After "Removed/Approved", the next site should be displayed.
(Note if not, it could drive the DB to inconsistency, can a site be approved and removed?)

**Screenshots**
![image](https://user-images.githubusercontent.com/47473455/93055148-c331ab80-f66a-11ea-8901-1c249a38e23b.png)

**Additional context**
If operation performed 4/5 times the application goes down.
Relevant logs:

```sh
flask_1  |     rv = self.dispatch_request()
flask_1  |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
flask_1  |     return self.view_functions[rule.endpoint](**req.view_args)
flask_1  |   File "./app/view/pages/benchmark_search.py", line 29, in search_benchmark
flask_1  |     page = factory.generate_page(
flask_1  |   File "./app/view/page_factory.py", line 74, in generate_page
flask_1  |     logged_in=controller.is_authenticated(),
flask_1  |   File "./app/controller/io_controller.py", line 329, in is_authenticated
flask_1  |     return authenticator.is_authenticated()
flask_1  |   File "./app/controller/authenticator.py", line 76, in is_authenticated
flask_1  |     if not self._token_expired():
flask_1  |   File "./app/controller/authenticator.py", line 142, in _token_expired
flask_1  |     if not self._refresh_token():
flask_1  |   File "./app/controller/authenticator.py", line 130, in _refresh_token
flask_1  |     user['info'] = session['user']['info']
flask_1  | TypeError: 'NoneType' object does not support item assignment
```

**Comment by TheChristophe** [comment]
Did you just restart the node?

**Comment by TheChristophe** [comment]
Also note, the stacktrace you posted is relevant to another issue (see #42).

**Comment by BorjaEst** [comment]
Hi, yes!

Looks we are just crossing the work, let me know when you finish!

**Comment by TheChristophe** [comment]
> [Additional context et al]
I was getting a few odd behaviours in the code, but they seem to have stopped. I believe the crashes are unrelated to the site review/to this issue, and are due to whatever happens in issue #42. Please reopen if the above issues still persist.

> If the step is repeated several times, it might break the server (but it goes up after some minutes again)

I think the server going down would just have been me restarting the server while addressing another issue, earlier.

> The site reports should be available at the search lists

This seems to work (at least it does now)

> Confirmation that the site was Removed/Approved only if it really happened!

It actually should be happening every time, but you were probably just seeing the same report over and over, because it was fetching the first report, even if that had already been reviewed (this was fixed in 4e473b8)

> After "Removed/Approved", the next site should be displayed.

This is technically possible to be implemented, but for now I believe disabling the form buttons and having the user click the site review button again should be fine (now that they get a new report every time).

> {screenshot}

It was displaying None as site name and description, this should be fixed in b85df7b0 and 45cbe9b4 respectively, but will require purging the database.

 - - -

> Looks we are just crossing the work, let me know when you finish!

I should be done now, I have also purged the database as mentioned above.

**Comment by BorjaEst** [comment]
It is good that now it is not possible to click on "Remove" if it has been accepted.

However I cannot go to next site, always the same site is pointed:
![image](https://user-images.githubusercontent.com/47473455/93074207-53301f00-f684-11ea-83f9-b48af6992389.png)

**Comment by TheChristophe** [comment]
Fixed it by actually purging the old data/database, which couldn't happen before since it was running off memory. Unsure why the approve and remove buttons didn't work for that (broken) report, but it seems to work fine with proper new sites.
