### ISSUE TITLE
Admin menu is available to all users

### ISSUE THREAD

**Issue by BorjaEst** [EOSC-synergy/eosc-perf#47]
**Describe the bug**
I can access to the "Admin menu" without admin rights (even when I am not logged in).

**To Reproduce**
1. Open web browser using incognito function.
2. Access to web page.
3. You can see on the menue the tool "Admin menu", even you can access some areas without prompting the error "Not logged in"

**Expected behavior**
This area should be only available to administrators.

**Notes**
I would like totest this once is fixed:
Access to admin links when logged in without admin rights:
- https://193.144.46.238/info?text=No+benchmark+to+review
- https://193.144.46.238/info?text=No+site+to+review

**Comment by TheChristophe** [comment]
My apologies, this is not a bug in the software but a change I've made on the node in the admin check to always return True, because EGI always logs me in with Github and I don't see the admin menu otherwise. I have changed it back (and updated the repo on the server).
[ TODO: I will test again, the server is just slow to start ]

**Comment by TheChristophe** [comment]
NB the links you gave are not links to view reports, they're the resulting redirections to a generic message page that will always say the same text.
I have now tested accessing
https://193.144.46.238/view_report_fetch_first - Errors out (albeit in 502 gateway error fashion)
https://193.144.46.238/benchmark_review_fetch_first - Which returns a no-admin error if I am logged in, and a 'no reports to view' message if there is no result (this could be changed)
https://193.144.46.238/site_review_fetch_first - Also 502's if there's a report, says 'no reports to view' otherwise

**Comment by BorjaEst** [comment]
It looks now ok!
No more changes needed.

**Comment by TheChristophe** [comment]
I have pushed a change so that even if there's no reports, unauthorized users get an error message, and I've fixed the wrong checks in site and report review, probably introduced by a teammate of mine when copy-pasting my initial report code that I later fixed ;-)
